export { default as onDelete } from "./fetchEliminar";
export { onSubmitReg, onSubmitLog } from "./fetchRegister";
export { default as onSubmitX } from "./fetchX";
export { default as fetchPut } from "./fetchPut";
export { default as ObtenerUser } from "./obtenerUser";
export { default as fetchPost } from "./fetchPost";
export { default as fetchGet } from "./fetchGet";
export { default as useForm } from "./useForm";
export { formatear, formatearYear } from "./formatDate";
export { formData } from "./formData";
